/**
 * Helpers for the backend's `ChartKind` candid variant.
 *
 * `backend.ts` is auto-regenerated by Caffeine's bindgen on every build, so
 * hand-written helpers there get wiped. This module is the stable home.
 *
 * The candid native runtime shape is `{ line: null } | { candle: null }`.
 * Functions/values here are typed loosely (`any` / property-access casts) so
 * the module remains compatible no matter what TypeScript shape bindgen
 * emits for `ChartKind` — what matters is the runtime value.
 */

// biome-ignore lint/suspicious/noExplicitAny: decoupled from regenerated backend.ts ChartKind type
export const ChartKindLine: any = { line: null };
// biome-ignore lint/suspicious/noExplicitAny: decoupled from regenerated backend.ts ChartKind type
export const ChartKindCandle: any = { candle: null };

export function isLineKind(k: unknown): boolean {
  if (k === null || typeof k !== "object") return false;
  return (k as { line?: unknown }).line === null;
}

export function isCandleKind(k: unknown): boolean {
  if (k === null || typeof k !== "object") return false;
  return (k as { candle?: unknown }).candle === null;
}
