/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChartKind = IDL.Variant({
  'line' : IDL.Null,
  'candle' : IDL.Null,
});
export const LinePoint = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const ChartData = IDL.Record({
  'days' : IDL.Nat,
  'kind' : ChartKind,
  'line' : IDL.Vec(LinePoint),
  'candles' : IDL.Vec(Candle),
  'updatedAt' : IDL.Int,
  'coinId' : IDL.Text,
});
export const ApiResult_2 = IDL.Variant({ 'ok' : ChartData, 'err' : IDL.Text });
export const GlobalStats = IDL.Record({
  'btcDominance' : IDL.Float64,
  'totalMarketCap' : IDL.Float64,
  'activeCryptocurrencies' : IDL.Nat,
  'marketCapChangePercentage24h' : IDL.Float64,
  'totalVolume24h' : IDL.Float64,
  'markets' : IDL.Nat,
  'ethDominance' : IDL.Float64,
});
export const GlobalResponse = IDL.Record({
  'updatedAt' : IDL.Int,
  'stats' : GlobalStats,
});
export const ApiResult_1 = IDL.Variant({
  'ok' : GlobalResponse,
  'err' : IDL.Text,
});
export const SparklineData = IDL.Vec(IDL.Float64);
export const Coin = IDL.Record({
  'id' : IDL.Text,
  'ath' : IDL.Float64,
  'athChangePercentage' : IDL.Float64,
  'currentPrice' : IDL.Float64,
  'totalVolume' : IDL.Float64,
  'circulatingSupply' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'priceChangePercentage24h' : IDL.Float64,
  'priceChangePercentage1h' : IDL.Float64,
  'priceChangePercentage7d' : IDL.Float64,
  'low24h' : IDL.Float64,
  'totalSupply' : IDL.Float64,
  'high24h' : IDL.Float64,
  'sparkline7d' : SparklineData,
  'image' : IDL.Text,
  'marketCapRank' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const MarketResponse = IDL.Record({
  'page' : IDL.Nat,
  'coins' : IDL.Vec(Coin),
  'perPage' : IDL.Nat,
  'updatedAt' : IDL.Int,
});
export const ApiResult = IDL.Variant({
  'ok' : MarketResponse,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getCoinChart' : IDL.Func([IDL.Text, IDL.Nat, ChartKind], [ApiResult_2], []),
  'getGlobalStats' : IDL.Func([], [ApiResult_1], []),
  'getMarketData' : IDL.Func([], [ApiResult], []),
  'getMarketDataPage' : IDL.Func([IDL.Nat, IDL.Nat], [ApiResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChartKind = IDL.Variant({ 'line' : IDL.Null, 'candle' : IDL.Null });
  const LinePoint = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const ChartData = IDL.Record({
    'days' : IDL.Nat,
    'kind' : ChartKind,
    'line' : IDL.Vec(LinePoint),
    'candles' : IDL.Vec(Candle),
    'updatedAt' : IDL.Int,
    'coinId' : IDL.Text,
  });
  const ApiResult_2 = IDL.Variant({ 'ok' : ChartData, 'err' : IDL.Text });
  const GlobalStats = IDL.Record({
    'btcDominance' : IDL.Float64,
    'totalMarketCap' : IDL.Float64,
    'activeCryptocurrencies' : IDL.Nat,
    'marketCapChangePercentage24h' : IDL.Float64,
    'totalVolume24h' : IDL.Float64,
    'markets' : IDL.Nat,
    'ethDominance' : IDL.Float64,
  });
  const GlobalResponse = IDL.Record({
    'updatedAt' : IDL.Int,
    'stats' : GlobalStats,
  });
  const ApiResult_1 = IDL.Variant({ 'ok' : GlobalResponse, 'err' : IDL.Text });
  const SparklineData = IDL.Vec(IDL.Float64);
  const Coin = IDL.Record({
    'id' : IDL.Text,
    'ath' : IDL.Float64,
    'athChangePercentage' : IDL.Float64,
    'currentPrice' : IDL.Float64,
    'totalVolume' : IDL.Float64,
    'circulatingSupply' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'priceChangePercentage24h' : IDL.Float64,
    'priceChangePercentage1h' : IDL.Float64,
    'priceChangePercentage7d' : IDL.Float64,
    'low24h' : IDL.Float64,
    'totalSupply' : IDL.Float64,
    'high24h' : IDL.Float64,
    'sparkline7d' : SparklineData,
    'image' : IDL.Text,
    'marketCapRank' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const MarketResponse = IDL.Record({
    'page' : IDL.Nat,
    'coins' : IDL.Vec(Coin),
    'perPage' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const ApiResult = IDL.Variant({ 'ok' : MarketResponse, 'err' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getCoinChart' : IDL.Func(
        [IDL.Text, IDL.Nat, ChartKind],
        [ApiResult_2],
        [],
      ),
    'getGlobalStats' : IDL.Func([], [ApiResult_1], []),
    'getMarketData' : IDL.Func([], [ApiResult], []),
    'getMarketDataPage' : IDL.Func([IDL.Nat, IDL.Nat], [ApiResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };