/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiResult = { 'ok' : MarketResponse } |
  { 'err' : string };
export type ApiResult_1 = { 'ok' : GlobalResponse } |
  { 'err' : string };
export type ApiResult_2 = { 'ok' : ChartData } |
  { 'err' : string };
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'timestamp' : bigint,
}
export interface ChartData {
  'days' : bigint,
  'kind' : ChartKind,
  'line' : Array<LinePoint>,
  'candles' : Array<Candle>,
  'updatedAt' : bigint,
  'coinId' : string,
}
export type ChartKind = { 'line' : null } |
  { 'candle' : null };
export interface Coin {
  'id' : string,
  'ath' : number,
  'athChangePercentage' : number,
  'currentPrice' : number,
  'totalVolume' : number,
  'circulatingSupply' : number,
  'marketCap' : number,
  'name' : string,
  'priceChangePercentage24h' : number,
  'priceChangePercentage1h' : number,
  'priceChangePercentage7d' : number,
  'low24h' : number,
  'totalSupply' : number,
  'high24h' : number,
  'sparkline7d' : SparklineData,
  'image' : string,
  'marketCapRank' : bigint,
  'symbol' : string,
}
export interface GlobalResponse { 'updatedAt' : bigint, 'stats' : GlobalStats }
export interface GlobalStats {
  'btcDominance' : number,
  'totalMarketCap' : number,
  'activeCryptocurrencies' : bigint,
  'marketCapChangePercentage24h' : number,
  'totalVolume24h' : number,
  'markets' : bigint,
  'ethDominance' : number,
}
export interface LinePoint { 'timestamp' : bigint, 'price' : number }
export interface MarketResponse {
  'page' : bigint,
  'coins' : Array<Coin>,
  'perPage' : bigint,
  'updatedAt' : bigint,
}
export type SparklineData = Array<number>;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getCoinChart' : ActorMethod<[string, bigint, ChartKind], ApiResult_2>,
  'getGlobalStats' : ActorMethod<[], ApiResult_1>,
  'getMarketData' : ActorMethod<[], ApiResult>,
  'getMarketDataPage' : ActorMethod<[bigint, bigint], ApiResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];