/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LinePoint {
    timestamp: bigint;
    price: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Coin {
    id: string;
    ath: number;
    athChangePercentage: number;
    currentPrice: number;
    totalVolume: number;
    circulatingSupply: number;
    marketCap: number;
    name: string;
    priceChangePercentage24h: number;
    priceChangePercentage1h: number;
    priceChangePercentage7d: number;
    low24h: number;
    totalSupply: number;
    high24h: number;
    sparkline7d: SparklineData;
    image: string;
    marketCapRank: bigint;
    symbol: string;
}
export type ApiResult = {
    __kind__: "ok";
    ok: MarketResponse;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_2 = {
    __kind__: "ok";
    ok: ChartData;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_1 = {
    __kind__: "ok";
    ok: GlobalResponse;
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface GlobalResponse {
    updatedAt: bigint;
    stats: GlobalStats;
}
export interface MarketResponse {
    page: bigint;
    coins: Array<Coin>;
    perPage: bigint;
    updatedAt: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Candle {
    low: number;
    high: number;
    close: number;
    open: number;
    timestamp: bigint;
}
export type SparklineData = Array<number>;
export interface ChartData {
    days: bigint;
    kind: ChartKind;
    line: Array<LinePoint>;
    candles: Array<Candle>;
    updatedAt: bigint;
    coinId: string;
}
export interface GlobalStats {
    btcDominance: number;
    totalMarketCap: number;
    activeCryptocurrencies: bigint;
    marketCapChangePercentage24h: number;
    totalVolume24h: number;
    markets: bigint;
    ethDominance: number;
}
export enum ChartKind {
    line = "line",
    candle = "candle"
}
export interface backendInterface {
    getCoinChart(coinId: string, days: bigint, kind: ChartKind): Promise<ApiResult_2>;
    getGlobalStats(): Promise<ApiResult_1>;
    getMarketData(): Promise<ApiResult>;
    getMarketDataPage(page: bigint, perPage: bigint): Promise<ApiResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ApiResult as _ApiResult, ApiResult_1 as _ApiResult_1, ApiResult_2 as _ApiResult_2, Candle as _Candle, ChartData as _ChartData, ChartKind as _ChartKind, GlobalResponse as _GlobalResponse, LinePoint as _LinePoint, MarketResponse as _MarketResponse } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCoinChart(arg0: string, arg1: bigint, arg2: ChartKind): Promise<ApiResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinChart(arg0, arg1, to_candid_ChartKind_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ApiResult_2_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinChart(arg0, arg1, to_candid_ChartKind_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ApiResult_2_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalStats(): Promise<ApiResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalStats();
                return from_candid_ApiResult_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalStats();
            return from_candid_ApiResult_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketData(): Promise<ApiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData();
                return from_candid_ApiResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData();
            return from_candid_ApiResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketDataPage(arg0: bigint, arg1: bigint): Promise<ApiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketDataPage(arg0, arg1);
                return from_candid_ApiResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketDataPage(arg0, arg1);
            return from_candid_ApiResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ApiResult_1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_1): ApiResult_1 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_2_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_2): ApiResult_2 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult): ApiResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ChartData_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartData): ChartData {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ChartKind_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartKind): ChartKind {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: bigint;
    kind: _ChartKind;
    line: Array<_LinePoint>;
    candles: Array<_Candle>;
    updatedAt: bigint;
    coinId: string;
}): {
    days: bigint;
    kind: ChartKind;
    line: Array<LinePoint>;
    candles: Array<Candle>;
    updatedAt: bigint;
    coinId: string;
} {
    return {
        days: value.days,
        kind: from_candid_ChartKind_n7(_uploadFile, _downloadFile, value.kind),
        line: value.line,
        candles: value.candles,
        updatedAt: value.updatedAt,
        coinId: value.coinId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GlobalResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GlobalResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MarketResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MarketResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChartData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChartData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ChartData_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    line: null;
} | {
    candle: null;
}): ChartKind {
    return "line" in value ? ChartKind.line : "candle" in value ? ChartKind.candle : value;
}
function to_candid_ChartKind_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartKind): _ChartKind {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartKind): {
    line: null;
} | {
    candle: null;
} {
    return value == ChartKind.line ? {
        line: null
    } : value == ChartKind.candle ? {
        candle: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
